name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000/tcp

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: mbstring, dom, fileinfo
          coverage: none

      - name: Validate composer files
        run: composer validate --no-check-all --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install prestissimo for faster installs
        run: composer global require hirak/prestissimo --no-ansi --no-interaction --prefer-dist --no-progress --no-suggest

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader

      - name: Lint project
        run: composer lint

      - name: Run tests
        run: composer coverage:clover
        env:
          DYNAMO_DB_HOST: localhost
          DYNAMO_DB_PORT: ${{ job.services.dynamodb.ports[8000] }}

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -ct ${{ secrets.CODECOV_TOKEN }}
